# ============================================================================
# STOCK WATCHLIST DATA (PUMP Dashboard)
# ============================================================================
# Each entry is a dict with full fundamental + catalyst data.
#
# Fields:
#   ticker, company, sector, price, mkt_cap, rev_ttm, rev_growth,
#   net_income, eps, pe, gross_margin, profit_margin, fcf_margin,
#   w52_low, w52_high, pumped, analyst_rating, price_target, profitable,
#   catalyst, risk, pot_1y, pot_2y, pot_5y
#
# pumped values : "YES", "PARTIAL", "NO"
# risk values   : "Low", "Medium", "High", "Very High"
# pot_Xy        : estimated potential % change (str like "+50%" or "-20% to +80%")
# ============================================================================

# Update this date each time the table is refreshed
LAST_UPDATED = "2026-06-19"

WATCHLIST_STOCKS = [
    {
        "ticker": "BE",
        "company": "Bloom Energy",
        "sector": "Energy",
        "price": 264,
        "mkt_cap": "75B",
        "rev_ttm": "2.45B",
        "rev_growth": "+56.5%",
        "net_income": "10M",
        "eps": -0.05,
        "pe": "N/A",
        "gross_margin": "29.6%",
        "profit_margin": "0.4%",
        "fcf_margin": "9.4%",
        "w52_low": 20,
        "w52_high": 323,
        "pumped": "YES (~13x)",
        "analyst_rating": "Buy",
        "price_target": 263,
        "profitable": "No",
        "catalyst": "Oracle/Brookfield data center deals",
        "risk": "High",
        "pot_1y": "-20% to +30%",
        "pot_2y": "-10% to +50%",
        "pot_5y": "+0% to +100%",
    },
    {
        "ticker": "CRDO",
        "company": "Credo Technology",
        "sector": "Semiconductors",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "1.34B",
        "rev_growth": "+206%",
        "net_income": "472M",
        "eps": 2.65,
        "pe": "—",
        "gross_margin": "68%",
        "profit_margin": "35.4%",
        "fcf_margin": "~0%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "YES (~5x)",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "Yes",
        "catalyst": "80%+ FY27 revenue guidance, AI connectivity",
        "risk": "High",
        "pot_1y": "-10% to +40%",
        "pot_2y": "+10% to +80%",
        "pot_5y": "+50% to +200%",
    },
    {
        "ticker": "VRT",
        "company": "Vertiv Holdings",
        "sector": "Industrials",
        "price": 301,
        "mkt_cap": "115B",
        "rev_ttm": "10.8B",
        "rev_growth": "+29%",
        "net_income": "1.56B",
        "eps": 3.98,
        "pe": "75.5x",
        "gross_margin": "—",
        "profit_margin": "14.4%",
        "fcf_margin": "—",
        "w52_low": 107,
        "w52_high": 380,
        "pumped": "YES (~3x)",
        "analyst_rating": "Buy",
        "price_target": 377,
        "profitable": "Yes",
        "catalyst": "AI data center power & cooling",
        "risk": "Medium",
        "pot_1y": "-10% to +30%",
        "pot_2y": "+0% to +60%",
        "pot_5y": "+30% to +150%",
    },
    {
        "ticker": "FIX",
        "company": "Comfort Systems",
        "sector": "Industrials",
        "price": 1844,
        "mkt_cap": "64.8B",
        "rev_ttm": "10.1B",
        "rev_growth": "+29.5%",
        "net_income": "1.22B",
        "eps": 34.64,
        "pe": "53.2x",
        "gross_margin": "25.1%",
        "profit_margin": "12.1%",
        "fcf_margin": "~0%",
        "w52_low": 469,
        "w52_high": 2074,
        "pumped": "YES (~4x)",
        "analyst_rating": "Strong Buy",
        "price_target": 2026,
        "profitable": "Yes",
        "catalyst": "Data center HVAC & electrical buildout",
        "risk": "Medium",
        "pot_1y": "-10% to +20%",
        "pot_2y": "+0% to +40%",
        "pot_5y": "+20% to +100%",
    },
    {
        "ticker": "RKLB",
        "company": "Rocket Lab",
        "sector": "Aerospace",
        "price": 110,
        "mkt_cap": "63.7B",
        "rev_ttm": "680M",
        "rev_growth": "+38.0%",
        "net_income": "-183M",
        "eps": -0.33,
        "pe": "N/A",
        "gross_margin": "—",
        "profit_margin": "Neg",
        "fcf_margin": "—",
        "w52_low": 25,
        "w52_high": 151,
        "pumped": "YES (~4x)",
        "analyst_rating": "Buy",
        "price_target": 105,
        "profitable": "No",
        "catalyst": "Neutron rocket, satellite constellation",
        "risk": "High",
        "pot_1y": "-30% to +40%",
        "pot_2y": "-10% to +100%",
        "pot_5y": "+50% to +300%",
    },
    {
        "ticker": "POWL",
        "company": "Powell Industries",
        "sector": "Industrials",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "1.13B",
        "rev_growth": "+9.1%",
        "net_income": "187M",
        "eps": 5.11,
        "pe": "—",
        "gross_margin": "30.1%",
        "profit_margin": "16.5%",
        "fcf_margin": "17%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "PARTIAL (~2-3x)",
        "analyst_rating": "Overweight",
        "price_target": 310,
        "profitable": "Yes",
        "catalyst": "$1.8B backlog, record $400M data center order",
        "risk": "Medium",
        "pot_1y": "+10% to +50%",
        "pot_2y": "+20% to +100%",
        "pot_5y": "+50% to +200%",
    },
    {
        "ticker": "LSCC",
        "company": "Lattice Semiconductor",
        "sector": "Semiconductors",
        "price": 136,
        "mkt_cap": "18.6B",
        "rev_ttm": "574M",
        "rev_growth": "+2.7%",
        "net_income": "20M",
        "eps": 0.14,
        "pe": "961x",
        "gross_margin": "68.4%",
        "profit_margin": "3.5%",
        "fcf_margin": "26%",
        "w52_low": 46,
        "w52_high": 156,
        "pumped": "PARTIAL (~3x from low)",
        "analyst_rating": "Strong Buy",
        "price_target": 147,
        "profitable": "Barely",
        "catalyst": "Cyclical recovery, edge AI, automotive",
        "risk": "Medium",
        "pot_1y": "+10% to +50%",
        "pot_2y": "+30% to +120%",
        "pot_5y": "+80% to +300%",
    },
    {
        "ticker": "LEU",
        "company": "Centrus Energy",
        "sector": "Energy",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "452M",
        "rev_growth": "-4.1%",
        "net_income": "61M",
        "eps": 3.02,
        "pe": "—",
        "gross_margin": "25.7%",
        "profit_margin": "13.4%",
        "fcf_margin": "-13.6%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "Yes",
        "catalyst": "$900M HALEU contract, monopoly nuclear fuel supplier",
        "risk": "Medium",
        "pot_1y": "+20% to +80%",
        "pot_2y": "+50% to +200%",
        "pot_5y": "+100% to +500%",
    },
    {
        "ticker": "NBIS",
        "company": "Nebius Group",
        "sector": "Technology",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "878M",
        "rev_growth": "+453%",
        "net_income": "918M*",
        "eps": 3.87,
        "pe": "—",
        "gross_margin": "83.9%",
        "profit_margin": "95%*",
        "fcf_margin": "-359%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "Mixed*",
        "catalyst": "Aschenbrenner stake, GPU cloud for AI",
        "risk": "High",
        "pot_1y": "-20% to +100%",
        "pot_2y": "+0% to +200%",
        "pot_5y": "+50% to +500%",
    },
    {
        "ticker": "FCEL",
        "company": "FuelCell Energy",
        "sector": "Energy",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "170M",
        "rev_growth": "+41.1%",
        "net_income": "-185M",
        "eps": -6.91,
        "pe": "N/A",
        "gross_margin": "-16%",
        "profit_margin": "Neg",
        "fcf_margin": "-77.6%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "No",
        "catalyst": "1.5 GW data center pipeline, carbon capture",
        "risk": "High",
        "pot_1y": "-40% to +100%",
        "pot_2y": "-20% to +200%",
        "pot_5y": "+0% to +500%",
    },
    {
        "ticker": "PLUG",
        "company": "Plug Power",
        "sector": "Energy",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "740M",
        "rev_growth": "+12.9%",
        "net_income": "-1.68B",
        "eps": -1.38,
        "pe": "N/A",
        "gross_margin": "-25.7%",
        "profit_margin": "Neg",
        "fcf_margin": "-88.3%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "PARTIAL (+330% 12mo)",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "No",
        "catalyst": "EBITDA+ target Q4 2026, hydrogen infra",
        "risk": "Very High",
        "pot_1y": "-50% to +100%",
        "pot_2y": "-30% to +200%",
        "pot_5y": "-50% to +500%",
    },
    {
        "ticker": "OKLO",
        "company": "Oklo Inc",
        "sector": "Energy",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "0",
        "rev_growth": "Pre-rev",
        "net_income": "-129M",
        "eps": -0.84,
        "pe": "N/A",
        "gross_margin": "N/A",
        "profit_margin": "N/A",
        "fcf_margin": "N/A",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "No",
        "catalyst": "DOE selection, Meta partnership, Sam Altman backed",
        "risk": "Very High",
        "pot_1y": "-40% to +100%",
        "pot_2y": "-20% to +300%",
        "pot_5y": "+0% to +1000%",
    },
    {
        "ticker": "SMR",
        "company": "NuScale Power",
        "sector": "Energy",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "19M",
        "rev_growth": "-15.0%",
        "net_income": "-386M",
        "eps": -2.92,
        "pe": "N/A",
        "gross_margin": "23.8%",
        "profit_margin": "Neg",
        "fcf_margin": "-4036%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "Neutral",
        "price_target": 12,
        "profitable": "No",
        "catalyst": "Only NRC-approved SMR design, TVA project",
        "risk": "Very High",
        "pot_1y": "-50% to +80%",
        "pot_2y": "-30% to +200%",
        "pot_5y": "+0% to +800%",
    },
    {
        "ticker": "VKTX",
        "company": "Viking Therapeutics",
        "sector": "Healthcare",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "0",
        "rev_growth": "Pre-rev",
        "net_income": "—",
        "eps": "—",
        "pe": "N/A",
        "gross_margin": "N/A",
        "profit_margin": "N/A",
        "fcf_margin": "N/A",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "No",
        "catalyst": "Phase III obesity drug enrolled, data 2027",
        "risk": "Very High",
        "pot_1y": "-50% to +100%",
        "pot_2y": "-30% to +300%",
        "pot_5y": "+0% to +1000%",
    },
    {
        "ticker": "ZNTL",
        "company": "Zentalis Pharma",
        "sector": "Healthcare",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "0",
        "rev_growth": "Pre-rev",
        "net_income": "-124M",
        "eps": -1.73,
        "pe": "N/A",
        "gross_margin": "N/A",
        "profit_margin": "N/A",
        "fcf_margin": "N/A",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "No",
        "catalyst": "Azenosertib pivotal trials, ovarian cancer",
        "risk": "Very High",
        "pot_1y": "-60% to +100%",
        "pot_2y": "-40% to +300%",
        "pot_5y": "-80% to +500%",
    },
    {
        "ticker": "BWXT",
        "company": "BWX Technologies",
        "sector": "Defense/Nuclear",
        "price": 186,
        "mkt_cap": "17B",
        "rev_ttm": "3.38B",
        "rev_growth": "+21.4%",
        "net_income": "345M",
        "eps": 3.75,
        "pe": "49.6x",
        "gross_margin": "22.7%",
        "profit_margin": "10.2%",
        "fcf_margin": "9.7%",
        "w52_low": 129,
        "w52_high": 233,
        "pumped": "PARTIAL (~2x from low)",
        "analyst_rating": "Buy",
        "price_target": 238,
        "profitable": "Yes",
        "catalyst": "Navy nuclear propulsion monopoly, $900M+ PCG acquisition, 77% backlog growth, SMR fuel demand",
        "risk": "Medium",
        "pot_1y": "+5% to +40%",
        "pot_2y": "+15% to +70%",
        "pot_5y": "+50% to +200%",
    },
    {
        "ticker": "LITE",
        "company": "Lumentum Holdings",
        "sector": "Optical / Networking",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "—",
        "rev_growth": "—",
        "net_income": "—",
        "eps": "—",
        "pe": "—",
        "gross_margin": "~35%",
        "profit_margin": "—",
        "fcf_margin": "—",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "YES (~2.4x, +140%)",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "Mixed",
        "catalyst": "NVIDIA optical partner; 800G/1.6T transceiver laser ramp. NB: lower-margin component supplier with legacy 3D-sensing/telecom drag — cyclical, trim at peak. Weaker quality than CRDO/COHR.",
        "risk": "High",
        "pot_1y": "-15% to +40%",
        "pot_2y": "+0% to +80%",
        "pot_5y": "+30% to +150%",
    },
    {
        "ticker": "CIEN",
        "company": "Ciena Corporation",
        "sector": "Optical / Networking",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "—",
        "rev_growth": "—",
        "net_income": "—",
        "eps": "—",
        "pe": "—",
        "gross_margin": "—",
        "profit_margin": "—",
        "fcf_margin": "—",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "PARTIAL (~1.5x)",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "Yes",
        "catalyst": "Coherent/long-haul optical + growing DCI (data-center interconnect) AI segment. NB: carrier-spend exposed (lumpier, slower than hyperscaler capex) but DCI is a genuine AI play. Mid-cycle, cyclical.",
        "risk": "Medium",
        "pot_1y": "-10% to +35%",
        "pot_2y": "+0% to +70%",
        "pot_5y": "+30% to +120%",
    },
    {
        "ticker": "EME",
        "company": "EMCOR Group",
        "sector": "Industrials",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "—",
        "rev_growth": "—",
        "net_income": "—",
        "eps": "—",
        "pe": "—",
        "gross_margin": "—",
        "profit_margin": "—",
        "fcf_margin": "—",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "PARTIAL",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "Yes",
        "catalyst": "Mega-campus EPC (electrical + mechanical) for AI data centers. Diversified across DC, industrial, healthcare, reshoring — NOT the single-theme late-cycle play FIX is. Mid-cycle, cyclical.",
        "risk": "Medium",
        "pot_1y": "-5% to +30%",
        "pot_2y": "+10% to +60%",
        "pot_5y": "+30% to +120%",
    },
    {
        "ticker": "BEP",
        "company": "Brookfield Renewable",
        "sector": "Energy",
        "price": "—",
        "mkt_cap": "—",
        "rev_ttm": "6.34B",
        "rev_growth": "-3.2%",
        "net_income": "-1.07B",
        "eps": -0.31,
        "pe": "N/A",
        "gross_margin": "48.7%",
        "profit_margin": "-16.9%",
        "fcf_margin": "-85%",
        "w52_low": "—",
        "w52_high": "—",
        "pumped": "NO",
        "analyst_rating": "—",
        "price_target": "—",
        "profitable": "No",
        "catalyst": "Hyperscaler PPAs, Boralex acquisition",
        "risk": "Low",
        "pot_1y": "+5% to +20%",
        "pot_2y": "+10% to +40%",
        "pot_5y": "+30% to +80%",
    },
]

# ============================================================================
# WATCHLIST COLUMN DEFINITIONS
# (header label, dict key, description)
# ============================================================================

WATCHLIST_COLUMNS = [
    ("Ticker",   "ticker",         "Stock ticker symbol"),
    ("Company",  "company",        "Company name"),
    ("Sector",   "sector",         "Industry sector"),
    ("Price",    "price",          "Current price (USD)"),
    ("Mkt Cap",  "mkt_cap",        "Market Capitalization"),
    ("Rev TTM",  "rev_ttm",        "Revenue, Trailing Twelve Months"),
    ("Rev Grw",  "rev_growth",     "Revenue Growth, Year-over-Year"),
    ("Net Inc",  "net_income",     "Net Income, Trailing Twelve Months"),
    ("EPS",      "eps",            "Earnings Per Share"),
    ("PE",       "pe",             "Price-to-Earnings ratio"),
    ("GM",       "gross_margin",   "Gross Margin"),
    ("PM",       "profit_margin",  "Profit Margin"),
    ("FCF M",    "fcf_margin",     "Free Cash Flow Margin"),
    ("52W Lo",   "w52_low",        "52-Week Low price"),
    ("52W Hi",   "w52_high",       "52-Week High price"),
    ("Pumped?",  "pumped",         "Whether the stock already had a major run"),
    ("Rating",   "analyst_rating", "Analyst consensus rating"),
    ("PT",       "price_target",   "Analyst consensus Price Target"),
    ("Profit?",  "profitable",     "Whether the company is currently profitable"),
    ("Risk",     "risk",           "Risk level: Low / Medium / High / Very High"),
    ("Pot 1Y",   "pot_1y",         "Estimated potential price change over 1 year"),
    ("Pot 2Y",   "pot_2y",         "Estimated potential price change over 2 years"),
    ("Pot 5Y",   "pot_5y",         "Estimated potential price change over 5 years"),
    ("Catalyst", "catalyst",       "Key catalyst or thesis"),
]

# ============================================================================
# RISK-BASED ROW COLORS FOR HTML RENDERING
# ============================================================================

WATCHLIST_RISK_COLORS = {
    "Low":       "#E8F5E9",  # Soft green
    "Medium":    "#FFF8E1",  # Soft amber
    "High":      "#FFF3E0",  # Soft orange
    "Very High": "#FFEBEE",  # Soft red
}


def get_watchlist_row_color(risk):
    """Return HTML background color based on risk level."""
    for key, color in WATCHLIST_RISK_COLORS.items():
        if key in str(risk):
            return color
    return "#FFFFFF"
